@echo off

echo Uninstalling Clipchamp...
winget uninstall --id 9P1J8S7CCWWT
echo Uninstalling Cortana...
winget uninstall --id 9NFFX4SZZ23L
echo Uninstalling Camera...
winget uninstall --id 9WZDNCRFJBBG
echo Uninstalling Clock...
winget uninstall --id 9WZDNCRFJ3PR
echo Uninstalling Feedback Hub...
winget uninstall --id 9NBLGGH4R32N
echo Uninstalling Get Help...
winget uninstall --id 9PKDZBMV1H3T
echo Uninstalling Mail and Calendar...
winget uninstall --id 9WZDNCRFHVQM
echo Uninstalling Maps...
winget uninstall --id 9WZDNCRDTBVB
echo Uninstalling Media Player...
winget uninstall --id 9WZDNCRFJ3PT
echo Uninstalling OneDrive...
winget uninstall --id 9WZDNCRFJ1P3
winget uninstall --id Microsoft.OneDrive
echo Uninstalling Teams...
winget uninstall --id 9WZDNCRFJBMP
winget uninstall --id XP8BT8DW290MPQ
winget uninstall --id Microsoft.Teams
echo Uninstalling To Do...
winget uninstall --id 9NBLGGH5R558
echo Uninstalling Films and TV...
winget uninstall --id 9WZDNCRFJ3P2
echo Uninstalling News...
winget uninstall --id 9WZDNCRFHVFW
echo Uninstalling Quick Assist...
winget uninstall --id 9P7BP5VNWKX5
echo Uninstalling Sticky Notes...
winget uninstall --id 9NBLGGH4QGHW
echo Uninstalling Tips...
winget uninstall --id 9WZDNCRDTBJJ
echo Uninstalling Voice Recorder...
winget uninstall --id 9WZDNCRFHWKN
echo Uninstalling Weather...
winget uninstall --id 9WZDNCRFJ3Q2

echo.
echo Uninstallation complete!
echo Press any key to exit...
pause>nul